branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: for_love
  branch: master
  default_ec2_keyname: null
  default_platform: Ruby 2.5 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: origin
  sc: git
  workspace_type: Application
